# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
exclude: [node_modules]

# Site Settings
title: "ChemSymphoria2024"
# email: "devfest@gdg.org.ua"
# description: "GDG DevFest is a set of events all around the world"
# baseurl: "/"
url: "https://chemsymphoria2024.github.io"




# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/gallery/", text: Gallery}

 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a Sponsor"}
# rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a Sponsor"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "CHEM SYMPHORIA <typeout>"
eventDate: "December 2-4, 2024"
# typeoutTextValues: '"Chemistry", "Science", "Research", "Presentations"'
typeoutTextValues: '"IISER PUNE"'
# typeoutFallback: "Season"
# heroButtons:


# About Block
aboutTitle: "About Chem Symphoria"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "ChemSymphoria is an in-house symposium of the Department of Chemistry at IISER Pune. The symposium aims to celebrate Chemistry Day within the department and features presentations by distinguished scientists focusing on various aspects of innovative research in science and technology. The platform also hosts presentations by final-year Ph.D. students, postdocs, industry and academia alumni. Active involvement from students and faculty of other departments at IISER Pune has been an integral part of ChemSymphoria over the years." }
#  - {title: "E", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "From diverse scientific disciplines"}
 - {count: "20", specialCharacter: "+", info: "hours", detail: "Scientific presentation and discussion sessions"}
 - {count: "35", specialCharacter: "+", info: "speakers", detail: "Representing various disciplines of chemistry"}
#  - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"


# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
# venueTitle: "C.V. Raman Auditorium"
venueTitle: "To be updated soon..."

venueFeatures: ["ISER Pune, Dr. Homi Bhabha Road, Pune 411008, India"]



# Partners Block
# organizersTitle: "Organizers"
partnersTitle: "Sponsors"
# partnersC4sponsorsButton: "Become a sponsor"


# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "ChemPhilic Team"
aboutUs: "We are a group of passionate PhD scholars with a deep love for chemistry.
 Each year, we organize an Intra-Departmental Chemistry symposium called 'ChemSymphoria', 
 at IISER Pune which provides an opportunity for students and researchers to showcase
  their work, engage in interdisciplinary discussions, and gain insights from renowned speakers.
   In addition to the conference, we host a range of academic and social events, including Freshers'
    Meets, Farewell Ceremonies, and various other departmental activities that strengthen our community 
    bonds. Whether you are an aspiring chemist or a seasoned researcher, the ChemPhilic Team offers a
     wealth of opportunities for professional development, networking, and forging lasting connections."
